"""The legend on the backlog graph is a filter (Mike, 2026-09-04: «а можешь фильтр добавить?»).

Every chip toggles a class of nodes; one predicate, `visible(node, filters)`, decides what
is on the canvas, and drawing, hover, search and selection all read its answer. The page
is generated by `tools/backlog/build.py`, so it is built here from the fixture into a
temp dir and the produced HTML is inspected. The predicate itself is JavaScript: when
node.js is on PATH it is cut out of the page and executed; without node that test skips.

Since 2026-09-04 (Mike: «сделай тоже для них отдельный фильтр») the entries linked to
nothing are nodes too — task nodes with `lone: true`, one class more for the same
predicate — behind a chip that a first visit starts with hidden, so the picture does not
change until somebody asks.
"""
import json
import re
import shutil
import subprocess
import sys
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parents[3]
BUILD = ROOT / "tools" / "backlog" / "build.py"
FIXTURE = ROOT / "tools" / "backlog" / "fixture.md"

# What the first legend row always carries, whatever the board holds.
FIXED_CHIPS = {"CRITICAL", "HIGH", "MEDIUM", "LOW", "RESEARCH", "none", "adr", "phase", "arc",
               "lone"}


@pytest.fixture(scope="module")
def page(tmp_path_factory):
    out = tmp_path_factory.mktemp("graph")
    subprocess.run([sys.executable, str(BUILD), str(FIXTURE), f"--out={out}"],
                   check=True, cwd=ROOT, capture_output=True)
    html = (out / "graph.html").read_text(encoding="utf-8")
    data = json.loads((out / "graph.json").read_text(encoding="utf-8"))
    return html, data


def _chips(html):
    return re.findall(r'<button type="button" class="gk" data-filter="([^"]+)"', html)


def _classes_of(node):
    if node["k"] == "task":
        return {"none" if node["p"] == "—" else node["p"], node["sec"]} \
            | ({"lone"} if node.get("lone") else set())
    return {node["k"]}


def _run_js(tmp_path, html, fn_name, signature, tail):
    """Cut one top-level function out of the page and run `tail` after it under node."""
    fn = re.search(rf"^function {fn_name}\({signature}\)\{{.*?^\}}", html, re.S | re.M)
    assert fn, f"{fn_name}() not found in the page"
    script = tmp_path / f"{fn_name}.js"
    script.write_text(fn.group(0) + "\n" + tail, encoding="utf-8")
    run = subprocess.run(["node", str(script)], capture_output=True, text=True, check=True)
    return json.loads(run.stdout)


def test_every_class_on_the_board_has_a_chip(page):
    html, data = page
    chips = _chips(html)
    assert len(chips) == len(set(chips)), "a chip key is duplicated"
    wanted = set().union(*(_classes_of(n) for n in data["nodes"])) | FIXED_CHIPS
    assert wanted <= set(chips), f"no chip for {wanted - set(chips)}"
    for group in ("kind", "sec"):
        assert f'data-all="{group}"' in html and f'data-none="{group}"' in html


def test_one_predicate_and_one_place_that_applies_it(page):
    html, _ = page
    assert html.count("function visible(") == 1
    assert html.count("function applyFilters(") == 1
    # search and selection consult the same answer instead of re-deciding it
    assert "const hit=j=>shown[j]&&" in html
    assert "if(!shown[i])return;" in html


def test_every_embedded_node_carries_what_the_predicate_reads(page):
    html, data = page
    embedded = re.search(r"<script>const DATA=(\{.*?\});</script>", html, re.S)
    assert embedded, "DATA is not embedded in the page"
    nodes = json.loads(embedded.group(1))["nodes"]
    assert nodes, "the fixture produced no linked nodes — the test is vacuous"
    assert [n["id"] for n in nodes] == [n["id"] for n in data["nodes"]]
    for n in nodes:
        assert {"k", "p", "sec"} <= n.keys(), n


SAMPLE = [
    {"id": "A", "k": "task", "p": "HIGH", "sec": "OPEN"},
    {"id": "B", "k": "task", "p": "—", "sec": "DONE"},
    {"id": "C", "k": "adr", "p": "—", "sec": "decision"},
    {"id": "D", "k": "task", "p": "LOW", "sec": "OPEN", "lone": True, "deg": 0},
]
# (hidden keys, expected visibility of A, B, C, D)
CASES = [
    ([], [True, True, True, True]),
    (["HIGH", "arc"], [False, True, True, True]),
    (["DONE"], [True, False, True, True]),
    (["adr", "none"], [True, False, False, True]),
    (["lone"], [True, True, True, False]),          # the lone chip hides only lone nodes
    (["LOW"], [True, True, True, False]),           # a lone node is a task: its priority applies
    (["OPEN"], [False, True, True, False]),         # and so does its section
]


def test_the_predicate_hides_by_priority_section_and_kind(page, tmp_path):
    if shutil.which("node") is None:
        pytest.skip("node.js is not on PATH")
    html, _ = page
    got = _run_js(tmp_path, html, "visible", "n,filters",
                  "const S=" + json.dumps(SAMPLE, ensure_ascii=False)
                  + ";\nconst C=" + json.dumps([c[0] for c in CASES])
                  + ";\nconsole.log(JSON.stringify(C.map(h=>S.map(n=>visible(n,new Set(h))))));\n")
    assert got == [c[1] for c in CASES]


# ------------------------------------------------------------- linked to nothing
def test_unlinked_entries_are_nodes_of_their_own_class(page):
    html, data = page
    lone = [n for n in data["nodes"] if n.get("lone")]
    linked = [n for n in data["nodes"] if not n.get("lone")]
    assert lone and linked, "the fixture must produce both kinds or the test is vacuous"
    # one node per name; the backward-compatible `unlinked` list keeps every occurrence
    assert [n["id"] for n in lone] == sorted(set(data["unlinked"]))
    assert len(data["unlinked"]) >= len(lone)
    assert not set(n["id"] for n in lone) & set(n["id"] for n in linked)
    for n in lone:
        assert n["k"] == "task" and n["deg"] == 0 and n["lone"] is True, n
        assert {"id", "k", "p", "sec", "d", "ln", "deg", "x", "y"} <= n.keys(), n
    assert all(n["deg"] > 0 for n in linked)
    # the page embeds the same nodes, and the chip counts them
    embedded = json.loads(re.search(r"<script>const DATA=(\{.*?\});</script>", html, re.S).group(1))
    assert sum(1 for n in embedded["nodes"] if n.get("lone")) == len(lone)
    m = re.search(r'data-filter="lone" data-group="kind" aria-pressed="true">.*?<b class="n">(\d+)</b>',
                  html, re.S)
    assert m and int(m.group(1)) == len(lone)


def test_a_first_visit_hides_the_lone_class(page, tmp_path):
    html, _ = page
    # The initial set is a pure function of the two stored strings; the page calls it once.
    assert html.count("function initialFilters(") == 1
    assert "hidden=initialFilters(localStorage.getItem(FKEY),localStorage.getItem(OLDKEY))" in html
    assert "let hidden=new Set(['lone']);" in html          # the fallback when storage throws
    # a stored empty set must survive as "hide nothing": it is written, never removed
    assert "localStorage.setItem(FKEY,JSON.stringify([...hidden]))" in html
    assert "localStorage.removeItem(FKEY)" not in html
    if shutil.which("node") is None:
        pytest.skip("node.js is not on PATH")
    cases = [(None, None), ("[]", None), ('["HIGH"]', None), (None, '["HIGH"]'),
             ("not json", None), ("not json", '["DONE"]')]
    got = _run_js(tmp_path, html, "initialFilters", "stored,legacy",
                  "const C=" + json.dumps(cases)
                  + ";\nconsole.log(JSON.stringify(C.map(([s,l])=>[...initialFilters(s,l)].sort())));\n")
    assert got == [["lone"],            # nothing stored: the ring starts hidden
                   [],                  # a stored choice to hide nothing wins
                   ["HIGH"],            # a stored choice that shows the ring wins
                   ["HIGH", "lone"],    # a set from before the class existed: migrated, ring hidden
                   ["lone"],            # corrupt storage: the default
                   ["DONE", "lone"]]    # corrupt new key, readable old one


def test_the_list_under_the_canvas_carries_what_the_predicate_reads(page):
    html, data = page
    items = re.findall(r'<li class="item" data-pri="([^"]*)" data-sec="([^"]*)" data-ref="([^"]*)">'
                       r'<div class="hd">.*?<code><a data-node="([^"]*)">', html, re.S)
    assert len(items) == len(data["unlinked"])
    assert sorted(ref for _, _, ref, _ in items) == sorted(data["unlinked"])
    assert all(ref == node for _, _, ref, node in items)
    # the list is filtered by the same predicate as the canvas, as a task without the lone flag
    assert "visible({k:'task',p:li.dataset.pri,sec:li.dataset.sec},hidden)" in html
    assert 'id="lonecnt"' in html
