"""The legend on the backlog graph is a filter (Mike, 2026-09-04: «а можешь фильтр добавить?»).

Every chip toggles a class of nodes; one predicate, `visible(node, filters)`, decides what
is on the canvas, and drawing, hover, search and selection all read its answer. The page
is generated by `tools/backlog/build.py`, so it is built here from the fixture into a
temp dir and the produced HTML is inspected. The predicate itself is JavaScript: when
node.js is on PATH it is cut out of the page and executed; without node that test skips.
"""
import json
import re
import shutil
import subprocess
import sys
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parents[3]
BUILD = ROOT / "tools" / "backlog" / "build.py"
FIXTURE = ROOT / "tools" / "backlog" / "fixture.md"

# What the first legend row always carries, whatever the board holds.
FIXED_CHIPS = {"CRITICAL", "HIGH", "MEDIUM", "LOW", "RESEARCH", "none", "adr", "phase", "arc"}


@pytest.fixture(scope="module")
def page(tmp_path_factory):
    out = tmp_path_factory.mktemp("graph")
    subprocess.run([sys.executable, str(BUILD), str(FIXTURE), f"--out={out}"],
                   check=True, cwd=ROOT, capture_output=True)
    html = (out / "graph.html").read_text(encoding="utf-8")
    data = json.loads((out / "graph.json").read_text(encoding="utf-8"))
    return html, data


def _chips(html):
    return re.findall(r'<button type="button" class="gk" data-filter="([^"]+)"', html)


def _classes_of(node):
    if node["k"] == "task":
        return {"none" if node["p"] == "—" else node["p"], node["sec"]}
    return {node["k"]}


def test_every_class_on_the_board_has_a_chip(page):
    html, data = page
    chips = _chips(html)
    assert len(chips) == len(set(chips)), "a chip key is duplicated"
    wanted = set().union(*(_classes_of(n) for n in data["nodes"])) | FIXED_CHIPS
    assert wanted <= set(chips), f"no chip for {wanted - set(chips)}"
    for group in ("kind", "sec"):
        assert f'data-all="{group}"' in html and f'data-none="{group}"' in html


def test_one_predicate_and_one_place_that_applies_it(page):
    html, _ = page
    assert html.count("function visible(") == 1
    assert html.count("function applyFilters(") == 1
    # search and selection consult the same answer instead of re-deciding it
    assert "const hit=j=>shown[j]&&" in html
    assert "if(!shown[i])return;" in html


def test_every_embedded_node_carries_what_the_predicate_reads(page):
    html, data = page
    embedded = re.search(r"<script>const DATA=(\{.*?\});</script>", html, re.S)
    assert embedded, "DATA is not embedded in the page"
    nodes = json.loads(embedded.group(1))["nodes"]
    assert nodes, "the fixture produced no linked nodes — the test is vacuous"
    assert [n["id"] for n in nodes] == [n["id"] for n in data["nodes"]]
    for n in nodes:
        assert {"k", "p", "sec"} <= n.keys(), n


SAMPLE = [
    {"id": "A", "k": "task", "p": "HIGH", "sec": "OPEN"},
    {"id": "B", "k": "task", "p": "—", "sec": "DONE"},
    {"id": "C", "k": "adr", "p": "—", "sec": "decision"},
]
# (hidden keys, expected visibility of A, B, C)
CASES = [
    ([], [True, True, True]),
    (["HIGH", "arc"], [False, True, True]),
    (["DONE"], [True, False, True]),
    (["adr", "none"], [True, False, False]),
]


def test_the_predicate_hides_by_priority_section_and_kind(page, tmp_path):
    if shutil.which("node") is None:
        pytest.skip("node.js is not on PATH")
    html, _ = page
    fn = re.search(r"^function visible\(n,filters\)\{.*?^\}", html, re.S | re.M)
    assert fn, "visible() not found in the page"
    script = tmp_path / "visible.js"
    script.write_text(
        fn.group(0) + "\nconst S=" + json.dumps(SAMPLE, ensure_ascii=False)
        + ";\nconst C=" + json.dumps([c[0] for c in CASES])
        + ";\nconsole.log(JSON.stringify(C.map(h=>S.map(n=>visible(n,new Set(h))))));\n",
        encoding="utf-8")
    run = subprocess.run(["node", str(script)], capture_output=True, text=True, check=True)
    assert json.loads(run.stdout) == [c[1] for c in CASES]
